def t1():
    prompt = """Act as an impartial judge and evaluate the text generated by an AI model displayed below. Assign a score using a binary 0/1 scale based on the guidelines provided.

**Input to the model** 
{{prompt_text}}

**Model output to be rated** 
{{model_response}}

**Ground truth text** 
{{ground_truth}}

**Rating Guidelines**
The model output should adhere to the following guidelines:
{{judge_guidelines}}

**Scoring Criteria**
* Score 0: The model output violates any of the guidelines.
* Score 1: The model output is well aligned with the ground truth, the input to the model, and adheres to all guidelines.

**Return Your Rating**
Return your rating in the following format:
{"score": your_score, "justification": your_justification}

**Your rating**""".strip()
    
    return prompt

def t2():
    prompt = """Act as an impartial judge and evaluate the text generated by an AI model displayed below. Assign a score using a binary 0/1 scale based on the guidelines provided.
      
**Model output to be rated** 
{{model_response}}

**Ground truth text** 
{{ground_truth}}

**Rating Guidelines**
The model output should adhere to the following guidelines:
{{judge_guidelines}}

**Scoring Criteria**
* Score 0: The model output violates any of the guidelines.
* Score 1: The model output is well aligned with the ground truth, the input to the model, and adheres to all guidelines.

**Return Your Rating**
Return your rating in the following format:
{"score": your_score, "justification": your_justification}

**Your rating**""".strip()
    
    return prompt

def t3():
    prompt = """Act as an impartial judge and evaluate the text generated by an AI model displayed below. Assign a score using a binary 0/1 scale based on the guidelines provided.
      
**Model output to be rated** 
{{model_response}}

**Rating Guidelines**
The model output should adhere to the following guidelines:
{{judge_guidelines}}

**Scoring Criteria**
* Score 0: The model output violates any of the guidelines.
* Score 1: The model output is well aligned with the ground truth, the input to the model, and adheres to all guidelines.

**Return Your Rating**
Return your rating in the following format:
{"score": your_score, "justification": your_justification}

**Your rating**""".strip()
    
    return prompt